# name: Snake

# on:
#   schedule:
#     - cron: "0 0 * * *"

#   # allows to manually run the job at any time
#   workflow_dispatch:

# jobs:
#   generate:
#     runs-on: ubuntu-latest
#     timeout-minutes: 10

#     steps:
#       - name: generate github-contribution-grid-snake.svg
#         uses: Platane/snk/svg-only@v2
#         with:
#           github_user_name: stermso
#           outputs: |
#             dist/profile-snake-contrib/github-contribution-grid-snake.svg
#             dist/profile-snake-contrib/github-contribution-grid-snake-dark.svg?palette=github-dark

#       - name: push github-contribution-grid-snake.svg to the output branch
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: main
#           build_dir: dist
#           keep_history: true
#         env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


- uses: Platane/snk@v3
  with:
    # github user name to read the contribution graph from (**required**)
    # using action context var `github.repository_owner` or specified user
    github_user_name: ${{ github.repository_owner }}

    # list of files to generate.
    # one file per line. Each output can be customized with options as query string.
    #
    #  supported options:
    #  - palette:     A preset of color, one of [github, github-dark, github-light]
    #  - color_snake: Color of the snake
    #  - color_dots:  Coma separated list of dots color.
    #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
    #                 Exactly 5 colors are expected.
    outputs: |
      dist/profile-snake-contrib/github-snake.svg
      dist/profile-snake-contrib/github-snake-dark.svg?palette=github-dark
      dist/profile-snake-contrib/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9